<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW8YKCnx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW8YKCnx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW8YKCnx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW8YKCnx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerW8YKCnx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'W8YKCnx',
    'container.build_id' => '0f06afee',
    'container.build_time' => 1651952331,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW8YKCnx');
